version: '3.5'
services:
  mongodb:
    image: mongo:latest
    hostname: ${MONGO_HOST}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
